---
- hosts: webservers 
  become: True
  tasks:
    - name: Install prerequisites packages
      yum:
        name: unzip
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python
    - name: Download Tomcat
       get_url: url = https://archive.apache.org/dtst/tomcat/tomcat-8/v8.O.27/btn/apache-tomcat-8.O.27.tar.gz dest=/home/khanans/tomcat
    - name: Extract archive
       unarchive: src=/home/khanans/tomcat/apache-tomcat-8.O.27.tar .gz dest=/home/khanans/tomcat
    - name: start apache-tomcat-8.O.27
       shell: /home/khanans/tomcat/apache-tomcat-8.O.27/btn/startup.sh
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
